version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    environment:
      - VITE_GRAPHQL_URL=http://localhost:5001/graphql
      - VITE_GRAPHQL_WS_URL=ws://localhost:5001/graphql
    depends_on:
      - backend
    restart: unless-stopped
